# Generated by Django 6.0.7 on 2026-07-19 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('HOD', 'Head of Department'), ('CT', 'Class Teacher'), ('MNG', 'Manager'), ('AST', 'Assistant'), ('CO', 'Coordinator'), ('OTR', 'Other')], max_length=3)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.department')),
            ],
        ),
    ]
