# Generated by Django 6.0.7 on 2026-07-19 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='name',
            new_name='staff_name',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='role',
            new_name='staff_role',
        ),
    ]
