# Generated by Django 6.0.7 on 2026-07-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_rename_name_staff_staff_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_role',
            field=models.CharField(choices=[('HOD', 'Head of Department'), ('CT', 'Class Teacher'), ('AST', 'Assistant')], max_length=3),
        ),
    ]
