# Generated by Django 6.0.6 on 2026-06-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('producer', models.CharField(max_length=50)),
                ('platform', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('releaseDate', models.DateField()),
            ],
        ),
    ]
