# Generated by Django 6.0.6 on 2026-06-29 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='releaseDate',
            new_name='release_date',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='price',
            new_name='ticket_price',
        ),
    ]
