a = 'ABC def gHi'

print(a.upper())
print(a.lower())
print(a.capitalize())
print(a.title())
print(a.startswith('A'))
print(a.endswith('i'))
print(a.index('d'))
print(a.find('d'))
print(a.count('A'))
print(a.casefold())
print(len(a))
print(a.isalnum())
print(a.isalpha)
print(a.isnumeric())
print(a.isdecimal())
print(a.istitle())
print(a.isidentifier())
print(a.isprintable())