# Generated by Django 6.0.7 on 2026-07-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='student_year',
            field=models.IntegerField(choices=[(1, 'First Year'), (2, 'Second Year'), (3, 'Third Year')]),
        ),
    ]
