# Generated by Django 6.0.6 on 2026-06-29 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        ('catalog', '0002_rename_releasedate_movies_release_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.movies'),
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
