# Generated by Django 6.0.6 on 2026-07-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notif_type',
        ),
        migrations.AlterField(
            model_name='notification',
            name='text',
            field=models.CharField(max_length=255),
        ),
    ]
