# Generated by Django 6.0.6 on 2026-07-05 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pfp',
            field=models.ImageField(default='profile_pictures/DefaultPFP.webp', upload_to='profile_pictures/'),
        ),
    ]
